--SET FEEDBACK OFF
PROMPT FILE CREATED BY Pritesh Gandhi
PROMPT CREATING PART TABLE
PROMPT
SET TERMOUT OFF
DROP TABLE Part CASCADE CONSTRAINTS PURGE;
CREATE TABLE Part (
P# NVARCHAR2(4),
PNAME NVARCHAR2(20),
COLOR NVARCHAR2(15),
WEIGHT INTEGER,
CITY NVARCHAR2(25),
CONSTRAINT pk_part PRIMARY KEY(P#)
);

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P1','Nut','Red',12,'London');

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P2','Bolt','Green',17,'Paris');

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P3','Screw','Blue',17,'Rome');

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P4','Screw','Red',14,'London');

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P5','Cam','Blue',12,'Paris');

INSERT INTO Part(P#,PNAME,COLOR,WEIGHT,CITY)
VALUES('P6','Cog','Red',19,'London');


COMMIT;
SET TERMOUT ON
PROMPT PART TABLE CREATED AND POPULATED
SELECT Count(*) FROM Part;
SET FEEDBACK ON