SET FEEDBACK OFF
PROMPT FILE CREATED BY Pritesh Gandhi
PROMPT CREATING SUPPLIER TABLE
PROMPT
SET TERMOUT OFF
DROP TABLE Supplier CASCADE CONSTRAINTS PURGE;
CREATE TABLE Supplier(
S# NVARCHAR2(4),
SNAME NVARCHAR2(20),
STATUS INTEGER,
CITY NVARCHAR2(25),
CONSTRAINT pk_supplier PRIMARY KEY (S#)
);

INSERT INTO Supplier(S#,SNAME,STATUS,CITY)
VALUES('S1','Smith',20,'London');

INSERT INTO Supplier(S#,SNAME,STATUS,CITY)
VALUES('S2','Jones',10,'Paris');

INSERT INTO Supplier(S#,SNAME,STATUS,CITY)
VALUES('S3','Blake',30,'Paris');

INSERT INTO Supplier(S#,SNAME,STATUS,CITY)
VALUES('S4','Clark',20,'London');

INSERT INTO Supplier(S#,SNAME,STATUS,CITY)
VALUES('S5','Adams',30,'Athens');


COMMIT;
SET TERMOUT ON
PROMPT SUPPLIER TABLE CREATED AND POPULATED
SELECT Count(*) FROM Supplier;
SET FEEDBACK ON

